In [1]:
#Neural Network Classification
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.cross_validation import train_test_split
from sklearn.neural_network import MLPClassifier
from warnings import filterwarnings
filterwarnings('ignore')

raw_data = datasets.load_wine()
data = pd.DataFrame(data=raw_data.data, columns=raw_data.feature_names)
data['type'] = raw_data.target
X_train, X_test, Y_train, Y_test = train_test_split(data.iloc[:,:-1], data.type, test_size = 0.3, random_state = 0)

C:\Users\ACER\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn.grid_search import GridSearchCV

ann_pipeline = make_pipeline(MinMaxScaler(), MLPClassifier(random_state=0, max_iter=10))
param_grid = {
    "mlpclassifier__activation":['logistic', 'tanh', 'relu'],
    "mlpclassifier__solver":['lbfgs', 'sgd', 'adam'], 
    "mlpclassifier__alpha":10.0 ** -np.arange(1, 7),
    "mlpclassifier__hidden_layer_sizes":np.arange(13,21),
}

grid_ann = GridSearchCV(ann_pipeline, param_grid = param_grid, cv = 5)
grid_ann.fit(X_train, Y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('minmaxscaler', MinMaxScaler(copy=True, feature_range=(0, 1))), ('mlpclassifier', MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learnin...       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False))]),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'mlpclassifier__activation': ['logistic', 'tanh', 'relu'], 'mlpclassifier__solver': ['lbfgs', 'sgd', 'adam'], 'mlpclassifier__alpha': array([1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06]), 'mlpclassifier__hidden_layer_sizes': array([13, 14, 15, 16, 17, 18, 19, 20])},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [8]:
print('Best cross-validated accuracy score is {}'.format(grid_ann.best_score_))
best = grid_ann.best_params_
for k, v in grid_ann.best_params_.items(): 
    print("{:<40} : {}".format(k, v))

Best cross-validated accuracy score is 0.9838709677419355
mlpclassifier__activation                : logistic
mlpclassifier__alpha                     : 0.01
mlpclassifier__hidden_layer_sizes        : 20
mlpclassifier__solver                    : lbfgs


In [4]:
from sklearn.metrics import confusion_matrix
Y_pred = grid_ann.predict(X_test)
cf_ann = confusion_matrix(Y_test,Y_pred)
acc = np.mean(np.array(Y_test) == Y_pred)
print('accuracy = {}'.format(acc))
print(cf_ann)

accuracy = 1.0
[[19  0  0]
 [ 0 22  0]
 [ 0  0 13]]
